### ISSUE TITLE
The package could not be installed

### ISSUE THREAD

**Issue by AlkhudariGroup** [network-international/ngenius-woocommerce-plugin#11]
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin installation failed. 
[ngenius-woocommerce-plugin-master.zip](https://github.com/network-international/ngenius-woocommerce-plugin/files/12004185/ngenius-woocommerce-plugin-master.zip)

**Comment by reaganseaman** [comment]
Please unpack manually, then zip the inner "ngenius" folder, then upload that.

**Comment by AlkhudariGroup** [comment]
Please i need api secret key and also i need to active apple pay sdk
version

**Comment by AlkhudariGroup** [comment]
Can i know how many days i must  waiting your reply

**Comment by appinlet** [comment]
Hi @AlkhudariGroup,

For credentials, please kindly contact merchant support directly at https://www.network.ae/en/contactus
