### ISSUE TITLE
N-Genius Payment Gateway - This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated.

### ISSUE THREAD

**Issue by ravimakwanastrats360** [network-international/ngenius-woocommerce-plugin#13]
N-Genius Payment Gateway - This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage', it shouldn't be activated.

![issue1](https://github.com/network-international/ngenius-woocommerce-plugin/assets/92160615/c8663064-c507-4b6d-9b8c-a3bddf448f79)
![issue2](https://github.com/network-international/ngenius-woocommerce-plugin/assets/92160615/e2cd1ca1-fa69-4f04-9bf1-e474104a0868)

kindly help in above issue getting in wordpress woocommerce plugin

**Comment by ravimakwanastrats360** [comment]
@mu1ex @appinlet @mirabulula please help to fix above mention issue in woocommerce N-Genius Payment Gateway.

Thanks

**Comment by sms9092** [comment]
I hope this gets fixed soon, as our team would like to move to HPOS instead of legacy method. 
![image](https://github.com/network-international/ngenius-woocommerce-plugin/assets/22801058/8e2bb1cd-2951-44d0-b742-b90e9437c4ad)

**Comment by ravimakwanastrats360** [comment]
Thank you for your update.

**Comment by appinlet** [comment]
Hi @sms9092 and @ravimakwanastrats360

This issue is resolved in #16
