### ISSUE TITLE
Uncaught Error on Bool

### ISSUE THREAD

**Issue by sms9092** [network-international/ngenius-woocommerce-plugin#14]
2024-03-05T16:16:14+00:00 Critical Uncaught Error: Call to a member function get_id() on bool in /home/margwpvx/public_html/cakecraft/wp-content/plugins/ngenius/gateway/class-ngenius-gateway-payment.php:142  
Additional context
{
    "error": {
        "type": 1,
        "file": "\/home\/margwpvx\/public_html\/cakecraft\/wp-content\/plugins\/ngenius\/gateway\/class-ngenius-gateway-payment.php",
        "line": 142
    },
    "backtrace": [
        "",
        "#0 \/home\/margwpvx\/public_html\/cakecraft\/wp-content\/plugins\/ngenius\/gateway\/class-ngenius-gateway-payment.php(341): NgeniusGatewayPayment->process_order(Object(stdClass), Object(stdClass), 'PURCHASE')",
        "#1 \/home\/margwpvx\/public_html\/cakecraft\/wp-content\/plugins\/ngenius\/gateway\/class-ngenius-gateway.php(350): NgeniusGatewayPayment->order_update()",
        "#2 \/home\/margwpvx\/public_html\/cakecraft\/wp-includes\/class-wp-hook.php(324): NgeniusGateway->cron_order_update()",
        "#3 \/home\/margwpvx\/public_html\/cakecraft\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)",
        "#4 \/home\/margwpvx\/public_html\/cakecraft\/wp-includes\/plugin.php(565): WP_Hook->do_action(Array)",
        "#5 \/home\/margwpvx\/public_html\/cakecraft\/wp-cron.php(191): do_action_ref_array('ngenius_cron_or...', Array)",
        "#6 {main}",
        "thrown"
    ]
}

**Comment by appinlet** [comment]
Hi @sms9092 

This issue is resolved in #16
