### ISSUE TITLE
You are using fake 3Ds2 challenge Page - Error 

### ISSUE THREAD

**Issue by rifni** [network-international/ngenius-woocommerce-plugin#15]
Please advice me how to fix this issue  @mu1ex 
![Screenshot 2024-04-24 193356](https://github.com/network-international/ngenius-woocommerce-plugin/assets/61752289/7c2a867d-c1c9-4b0e-90fd-43b7cc3f646e)

**Comment by appinlet** [comment]
Hi @rifni,

Please note this is expected on the sandbox page, which simulates transactions.
