### ISSUE TITLE
Error! Invalid configuration.

### ISSUE THREAD

**Issue by Pnoble2088** [network-international/ngenius-woocommerce-plugin#5]
i have set up two servers, both with the same settings except for different hosting companies.

Payment configuration works fine on one but on the other, I keep getting the "Error! Invalid configuration."

i have compared both WordPress installation and server information. Everything seems ok on both sides but why it is not working on one is surprising.

Can you point me in any direction? Help is much appreciated.

thank you.

**Comment by appinlet** [comment]
@Pnoble2088 this issue may be fixed by https://github.com/network-international/ngenius-woocommerce-plugin/pull/6/files, as some servers expect the Content-Length header to be '0'. 

This will reflect as version 1.0.2 once released.
