### ISSUE TITLE
WP_Error could not be converted to string

### ISSUE THREAD

**Issue by pat771** [network-international/ngenius-woocommerce-plugin#9]
After activating the plugin, had a configuration error.
checked my log file and found the following error

 CRITICAL Uncaught Error: Object of class WP_Error could not be converted to string in /home/.../wp-content/plugins/ngenius/gateway/http/class-ngenius-gateway-http-transfer.php:47

Stack trace:
#0 /home/.../wp-content/plugins/ngenius/gateway/class-ngenius-gateway-payment.php(249): NgeniusGatewayHttpTransfer->create(Array)
#1 /home/.../wp-content/plugins/ngenius/gateway/class-ngenius-gateway-payment.php(321): NgeniusGatewayPayment->get_response_api('b62714db-1dfd-4...')
#2 /home/.../wp-content/plugins/ngenius/gateway/class-ngenius-gateway.php(321): NgeniusGatewayPayment->order_update()
#3 /home/.../wp-includes/class-wp-hook.php(308): NgeniusGateway->cron_order_update()
#4 /home/.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /home/.../public_html/lab in /home/gardencity/public_html/.../wp-content/plugins/ngenius/gateway/http/class-ngenius-gateway-http-transfer.php on line 47

please how do rectify this?

Thank you

**Comment by appinlet** [comment]
@pat771 this is addressed in https://github.com/network-international/ngenius-woocommerce-plugin/pull/10
